### PR TITLE
Use less restric rules for autoActivation

### PR DESCRIPTION
**Pull request by tferr**
@acardona, when auto-activation is enabled in the  TextEditor, this should make so that the auto-completion popup appears mid-word after the default 300ms delay.

This addresses what was discussed in https://github.com/scijava/script-editor/pull/56#issuecomment-1050968182

### CODE REVIEW

**Comment by acardona** [comment]
Thanks. Before I merge this: how does one deactivate automatic autocompletion from the GUI? I'd rather use control+space.

**Comment by tferr** [comment]
@acardona, I also dislike the automatic popup. Too distracting. But I am convinced everything is accurate now on the GUI side.

The only reason why that checkbox is active by default is for backwards compatibility with IJ macros. I thought, it would be easier to ask advanced users to turn it off, rather than asking newcomers to turn it on. 

Also, the behavior is as follows: Ctrl+Space _always_ works. When "Show completions without control+space" is selected, the popup window also appears after a 300ms pause, but it does not disable the Ctrl+Space invocation.

**Comment by tferr** [comment]
@acardona , can you give me write access to this repository? The release.sh script does not work if I am just a collaborator (or at least I don't get it to work).

**Comment by acardona** [comment]
Looks like now we can't merge this, must be the change in script-editor version.

**Comment by acardona** [comment]
Thanks!

**Pull request merged**
